### PR TITLE
Support zeitwork/Rails 6

### PR DESCRIPTION
**Pull request by searls**

### CODE REVIEW

**Comment by mhw** [comment]
I've picked up on this and got something that seems to be working in [this branch](https://github.com/mhw/good-migrations/tree/rails-6-support). The `on_file_autoloaded` method defined [here](https://github.com/fxn/zeitwerk/blob/master/lib/zeitwerk/loader/callbacks.rb#L9) seems to be called when a constant is being loaded, so I've hooked in to that. I also extracted the raise.

cc @fxn

**Comment by fxn** [comment]
Problem is, that is marked as `@private`!

**Comment by searls** [comment]
FWIW and while I don't love calling other people's private methods, the current state of the gem is "does not work", so it seems better to send to a private method if it upgrades the gem to "working" than to leave it broken

**Comment by mhw** [comment]
Ah, so it is! I'd overlooked the comment above it. 😞

**Comment by fxn** [comment]
No prob @mhw. That is kinda a shortcoming of Ruby and many languages FWIW, the method visibility is required for the project internals, but there is no formal way to mark, much less enforce "outside access".

**Comment by mhw** [comment]
Ok, I've got a second option that uses `autoloaded_constants` [here](https://github.com/mhw/good-migrations/tree/rails-6-support-take-2). 

Possible issues:
1. We detect the autoloading and raise at the end of the run, rather than stopping things as they happen.
2. I can't immediately see a simple way to get back from the constants that were autoloaded to the source files they were defined in, so the exception message currently shows the constant (e.g. `Pant`) instead of the pathname.
3. When `RAILS_ENV=production`, everything is eager loaded and `autoloader_constants` is unchanged at the end. So we wouldn't be able to raise during a production deployment this way, for example.

**Comment by fxn** [comment]
Good!

Regarding 3, this is already the case in this gem (see [Caveats](https://github.com/testdouble/good-migrations#caveats)). And you do not really want to raise in production anyway, this gem want developers in development mode to not autoload in migrations. To prevent/warn them from pushing them upstream, right?

Regarding 2, the user autoloaded in a migration, and given a constant name `Pant`, you know where do you have `pant.rb`. But that is of little use anyway, what matters is that there was a constant autoloaded and you probably know because you wrote the code in the migration that did so.

I cannot asses the importance of 1. I believe this gem wants to enforce best practices, if the user is told loudly a migration autoloads, maybe that is enough?

**Comment by mhw** [comment]
Yep, you’re right about 3 - I missed that. I’d also hope code wouldn’t get close to production if it contains migrations that don’t run.

I agree about the other two as well: they are changes in behaviour compared with how it works in prior versions of Rails, but they seem acceptable to me.

**Comment by searls** [comment]
@mhw I haven't looked at the code closely yet, but I'd personally push us to continue to raise ASAP and stop the migrations in their tracks if at all possible. Reason being that if it's just a warning it can & will be ignored (since the purpose of the gem is to help people catch an easy-to-overlook detail, having the gem's result be another-easy-to-overlook detail doesn't seem like a 
solution)

**Comment by fxn** [comment]
Take into account that the private callback runs also in production.

Zeitwerk is consistent auto vs eager loading: if they succeed, both do. If they fail, both do.

The first preliminary versions eager loaded using a recursive `require`. Shopify had Zeitwerk in production before they had it in development, and it was a surprise that later in development some constants could not be autoloaded because the files did not actually follow the conventions. For example, if you eager load `html.rb` with `require` and it defines `HTML`, that constant works in the code base. But in development mode, if the inflector does not have a rule is going to set an autoload for `Html`, and code referring to `HTML` breaks.

In that scenario, the correct behaviour is the latter, you expect an error.

For consistency, [Zeitwerk eager loads via `const_get`](https://github.com/fxn/zeitwerk/blob/master/lib/zeitwerk/loader.rb#L381). In a sense, it eager loads by autoloading everything.

**Comment by searls** [comment]
@fxn thanks so much for the continued advice & guidance in this thread. I appreciate your time explaining things

@mhw do you have what you need to take your branch a bit further and open a PR? If not, is there anything I can do to help you get there?

**Comment by LandonSchropp** [comment]
@searls @fxn @mhw Hey guys, this gem looks awesome, but having Zeitwerk support is a must-have for us. Anything I can do to help get this out the door?

**Pull request closed without merging**
